### ISSUE TITLE
requirements are not vlear enough in 'one-show' component

### ISSUE THREAD

**Issue by DrLiamKless** [suvelocity/TV-shows-boilerplate#1]
here =>  Beneath the Link that we provided to you create a div with the class like-div, in this div you will need to have an img with the class interaction-img. Show likedImg with alt='liked' when its liked. otherwise, show notLikedImg with alt='not liked'. You can see the pictures in the top of the code.

it is not clear your are still meaning to the one-show component. we understood it from looking at the tests.

**Comment by ShaharEli** [comment]
"After you finished the `Home` and the `Show` components tasks, you will need to fix the `OneShow` component" - written few the lines you described
