### ISSUE TITLE
Good chalenge! I have some things to improve though

### ISSUE THREAD

**Issue by zilbers** [suvelocity/TV-shows-boilerplate#2]
The css isnt responding well.
![problem](https://user-images.githubusercontent.com/67857576/95067390-7478ae00-070c-11eb-8b10-a2c2882010f2.png)

I would change the rating test to check toFixed, its more accurate to round the ratings that way.

It wasnt clest that the like function should be attached to the "like-div", I would explain it more clearly.

Other then that, a very well made test!

**Comment by ShaharEli** [comment]
It wasnt clest that the like function should be attached to the "like-div", I would explain it more clearly. --fixed


and check your classes the app is responsive:
![image](https://user-images.githubusercontent.com/65499638/95141231-4b423700-0779-11eb-9995-9cde41b653fb.png)
